switch from player to Entity
Try to avoid: java.lang.NoSuchMethodError: 'org.bukkit.entity.Player org.bukkit.event.entity.PlayerDeathEvent.getPlayer()'